### ISSUE TITLE
Plugin Compatibility Issue with Folia Environment

### ISSUE THREAD

**Issue by MCE-MatchaMC** [BrilliantTeam/NatureRevive#10]
*Version Information:
```
Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
Plugin Version: naturerevive-folia-2.0.0-shaded
```

*Error Reproduction:
```
Plugin not functioning
```

*Error Log:
```
[21:17:49 ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
java.lang.RuntimeException: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:74) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:47) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by RICE0707** [comment]
> *Version Information:
> 
> ```
> Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
> Plugin Version: naturerevive-folia-2.0.0-shaded
> ```
> 
> *Error Reproduction:
> 
> ```
> Plugin not functioning
> ```
> 
> *Error Log:
> 
> ```
> [21:17:49 ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
> java.lang.RuntimeException: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:74) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:47) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```

1.20.4 is not supported

**Comment by RICE0707** [comment]
> *Version Information:
> 
> ```
> Server Version: folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf
> Plugin Version: naturerevive-folia-2.0.0-shaded
> ```
> 
> *Error Reproduction:
> 
> ```
> Plugin not functioning
> ```
> 
> *Error Log:
> 
> ```
> [21:17:49 ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
> java.lang.RuntimeException: Could not load plugin 'nms-1_20_2 v${project.version}' as it is not marked as supporting Folia!
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:74) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:47) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at net.minecraft.server.Main.main(Main.java:131) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
>         at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
>         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> ```

naturerevive only supports Minecraft versions 1.17 to 1.20.2.

**Comment by RICE0707** [comment]
This is not an error. I will close this comment.

**Comment by MCE-MatchaMC** [comment]
Is there any estimate when 1.20.4 will be released?

**Comment by RICE0707** [comment]
> Is there any estimate when 1.20.4 will be released?

I cannot provide a specific timeline until our developers have time to maintain it or until we receive code contributions (PRs) from developers.
